### ISSUE TITLE
Struggle in compiling your project

### ISSUE THREAD

**Issue by olemde** [cotestatnt/esp-fs-webserver#16]
Hello cotestant.

thank you for this published project. Unfortunatly my knowledge is somehow to less to compile this project. I tested Arduino IDE and PlatformIO and goolged a lot.  Found no workaround which worked.
Do you have a workaround for rookies? 
Thanks
Ole

**Comment by cotestatnt** [comment]
Hi @olemde 
Could you add some additional info about the issue you encountered?

Wich example are you trying to compile? Wich platform (ESP32, ESP8266) are you using? The Arduino Core for the esp platform is up to date?

Consider that in this repository I have defined some actions and for each update, the examples are all recompiled automatically just to see if there are errors (with PlatoformIO).

This is the last check https://github.com/cotestatnt/esp-fs-webserver/actions/runs/3150110047/jobs/5517938849 and as you can see, all the examples defined compile both for ESP32 and for ESP8266
