### ISSUE TITLE
switch to different wifi

### ISSUE THREAD

**Issue by PatrickMons** [cotestatnt/esp-fs-webserver#17]
when you setup a connection to wifi everithing is fine but if you need to switch to another wifi end the name of new wifi is shorter than the previous one there is a problem because the last part of previous name is attacced to new one
example:
first ssid name "abcdefghilmn"
sec. ssid name "123456"
the secon ssid name will be: "123456ghilmn"
so the result is no wifi found and go again on ap mode

**Comment by cotestatnt** [comment]
Thanks @PatrickMons for your feedback.
I will check for a solution as soon as possible.
