### ISSUE TITLE
Bool options are not saved

### ISSUE THREAD

**Issue by Blueforcer** [cotestatnt/esp-fs-webserver#19]
bool options, wich will be displayed as switches 
![image](https://user-images.githubusercontent.com/31169771/220145480-1d2ec835-b9ed-4f01-bbeb-db71d250d484.png)

are not saved into the config.json. after i hit "save configuration" i check the config.json and the value is always false

**Comment by cotestatnt** [comment]
You are right @Blueforcer 

I'm sorry, but this is a bug introduced with new setup UI because I have accidentally deleted a row of code.
I will fix it immediatly and then I will draft a new release.

**Comment by cotestatnt** [comment]
Hi @Blueforcer 
I've just pushed the bugfix and some other functions for the /setup page (upload you custom logo file just clicking on default Espressif logo).

I want to do some more tests before drafting a new release, but if you want to fix this bug just overwrite the setup_htm.h file with the new one uploaded to Github.

**Comment by Blueforcer** [comment]
youre pretty fast man! i think i can wait until next release.
Btw is it possible to get a dropdown as an option? :-)

**Comment by cotestatnt** [comment]
> Btw is it possible to get a dropdown as an option? :-)

This is a feature I had already thought about, but it needs some work because the list can be of different data types.
I'll probably implement a version that allows you to use only strings or at most strings and numbers as the return value.

**Comment by Blueforcer** [comment]
Strings are fine, or maybe just saving the selected index? Then the user can compare whatever he likes.

**Comment by cotestatnt** [comment]
Goodmorning @Blueforcer 
The new release contains bug fix and the new method for dropdown listbox (only string values for the moment).

https://github.com/cotestatnt/esp-fs-webserver/releases/tag/1.2.0

**Comment by Blueforcer** [comment]
Oh boy, that was damn fast! Nice work!

**Comment by cotestatnt** [comment]
It was easier than i thought :)
