### ISSUE TITLE
Error run node minify.js to generate setup_htm.h

### ISSUE THREAD

**Issue by arimukhlas** [cotestatnt/esp-fs-webserver#26]
Hi @cotestatnt 

I have followed the instructions on [this link ](https://github.com/cotestatnt/esp-fs-webserver/issues/18#issuecomment-1436938221) 
- i put all files (app.js, setup.htm, and style.css) in folder build
- open a terminal in build folder
- run npm i
- run node minify.js

but I am getting an error 

![error](https://user-images.githubusercontent.com/95061616/230333228-c0381795-2244-4412-a814-0b7154d063b4.png)

- i also run npm install zlib

but the error still exist, can you give a hint?

**Comment by cotestatnt** [comment]
Hi @arimukhlas 

I've done some edits still to be released. Yoi need to download the latest commits as zip file
![image](https://user-images.githubusercontent.com/27758688/230341740-63460517-297f-42a0-babc-bd30277dc592.png)

The instructions needs to be updated. Once you have installed the latest avalaible zip you need to:
- open a terminal and set build folder as current. For example: 
 `cd <your_arduino_libraries_folder>esp-fs-webserver-master\setup-ui\data\build`
- run `npm i` to install script dependencies
- run `node minify.js`

The node.js script will generate a file named `setup_htm.h` inside build folder itself. Copy & paste this file in the `<your_arduino_libraries_folder>esp-fs-webserver-master\src` folder

**Comment by arimukhlas** [comment]
@cotestatnt 

![error](https://user-images.githubusercontent.com/95061616/232405790-824e75f0-1f8d-4827-a240-11d930f2aa43.png)

I have follow [your instruction](https://github.com/cotestatnt/esp-fs-webserver/issues/26#issuecomment-1498923297), but error still occur and setup_htm.h isnt generated, do you have any suggestion?
