### ISSUE TITLE
Interface not working using reverse proxy (HTTPS and/or subdirectory)

### ISSUE THREAD

**Issue by wilfredktlr** [cotestatnt/esp-fs-webserver#29]
I'm using Awtrix (which uses this library) to access it's webinterface but it does not work correctly with HTTPS and/or a subdirectory. I've explained the problem in the Awtrix issue below.

https://github.com/Blueforcer/awtrix-light/issues/236

**Comment by cotestatnt** [comment]
Hi @wilfredktlr 
I've just updated the `/setup` source file.
Now the protocol used for the internal links is the same as the webpage.

```
var url = new URL(`${window.location.protocol}//${window.location.hostname}/setup/config.json`);
```
