### ISSUE TITLE
Add more supported editor files (for example like .yaml)

### ISSUE THREAD

**Issue by erazor83** [cotestatnt/esp-fs-webserver#32]
Hi there.

For a project of mine it'd be great to also allow .yaml files in the editor.

I found the corresponding part in setup-ui/extras/edit.htm .
Can you supply an unminified version too?

Thanks and have a great day!

**Comment by erazor83** [comment]
>Can you supply an unminified version too?

**Comment by cotestatnt** [comment]
The file `edit.htm` is not mine. 
It comes from one of the ESP8266 webserver library example.

https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/FSBrowser/data/edit/index.htm

You could also serve directly this file from filesystem. In this way you can edit it directly online.
