### ISSUE TITLE
Difficult to load web-based configuration when the Wifi AP disappears for a long time after connected

### ISSUE THREAD

**Issue by arimukhlas** [cotestatnt/esp-fs-webserver#33]
Hi @cotestatnt 

1. I tried examples/customHTML on esp8266
after scanning and connecting to one of the detected Wifi networks, esp8226 gets an IP address

I tried turning off the wifi network router for a long time, so esp8266 would be WiFi.status() != WL_CONNECTED

I noticed if the esp8266 doesn't connect then it will try to reconnect, and if it fails then it will go into WIFI_AP mode
so wifi network 'ESP_AP' will reappear

but when my laptop is connected to the 'ESP_AP' of esp8266, I'm having trouble opening the web-based configuration on 192.168.4.1
but when i turn on wifi network router, web based configuration can open

is there a blocking function that makes the web based configuration unopenable??

2. Is it possible if WIFI_AP_STA mode is always active in all conditions, so we won't depend on the serial terminal to know the IP address if esp8266 is connected to Wifi Network

Thanks

**Comment by cotestatnt** [comment]
I'm sorry but I didn't realize this issue at all.
Have you solved it, or are you still having problems?
