### ISSUE TITLE
compilation error in platformio

### ISSUE THREAD

**Issue by jmcastillejo** [cotestatnt/esp-fs-webserver#36]
flatform espressif 5.3.0 mcu esp32-s2
arduino framework

src/main.cpp: In function 'void handleLed()':
src/main.cpp:88:44: error: 'class FSWebServer' has no member named 'getRequest'; did you mean 'handleRequest'?
   WebServerClass* webRequest = myWebServer.getRequest();

**Comment by cotestatnt** [comment]
With latest release, library should compile without problems with Platformio (tested)
