### ISSUE TITLE
Possibility to update files on filesystem via OTA

### ISSUE THREAD

**Issue by MichaelUray** [cotestatnt/esp-fs-webserver#4]
Is there actually a possibility to update files on filesystem via OTA?
It would be helpfull to transfer the web pages also via OTA.

**Comment by cotestatnt** [comment]
Hi @MichaelUray 
No, actually  this possibility is not implemented.

I will try to add in the next releases

**Comment by cotestatnt** [comment]
I've merged your pull request (thanks!!), so I'm going to close this issue.
Please re-open again if you still need.
