### ISSUE TITLE
WiFi SSID selection does not work by click on the radio button

### ISSUE THREAD

**Issue by MichaelUray** [cotestatnt/esp-fs-webserver#5]
Clicks on the green region work, on the red one not:
![2022-05-06_12-25-21_ESP_FS_webserver_-_Mozilla_Firefox](https://user-images.githubusercontent.com/25169478/167114658-d4b1d919-ebc0-40c3-a251-cb145b5772f3.png)

https://user-images.githubusercontent.com/25169478/167114794-c4164a3e-3ce1-49c0-a359-28834e381f0e.mp4

**Comment by cotestatnt** [comment]
Ok, thanks for your feedback.
It' needed to fix Javascript UI code in the setup webpage.

**Comment by cotestatnt** [comment]
This bug was fixed.
Thanks @MichaelUray
