### ISSUE TITLE
Minify procedure producing erroneous header

### ISSUE THREAD

**Issue by yconst** [cotestatnt/esp-fs-webserver#52]
The minify procedure described [here](https://github.com/cotestatnt/esp-fs-webserver/tree/master/built-in-webpages) generates the following erroneous header:

    #define SETUP_HTML_SIZE xxxx
    static const unsigned char SETUP_HTML[] PROGMEM = {
    ...

whereas it should be:

    #define SETUP_HTML_SIZE xxxx
    static const unsigned char _acsetup_min_htm[] PROGMEM = {
    ...

**Comment by cotestatnt** [comment]
Yes you are right.
I will correct the script as soon as I can
